### ISSUE TITLE
DF/F normalized traces

### ISSUE THREAD

**Issue by tawantayron** [inscopix/inscopix-cnmfe#63]
Dear developers,

I have a question. I would like to examine how Inscopix-CNMFe calculates the DF/F normalized traces for 1 photon calcium imaging data. If possible, could you indicate which part of the GitHub code this operation is done?

Thank you very much,

Best regards,

Tawan Carvalho

**Comment by brunoboivin** [comment]
Hi Tawan,
Inscopix CNMF-E currently offers two options for the units of the temporal traces: `dF` and `dF over noise`. You can find a description of these output units [here](https://github.com/inscopix/inscopix-cnmfe/blob/main/docs/parameter_tuning.md#output-units). The code used to scale the temporal traces is located [here](https://github.com/inscopix/inscopix-cnmfe/blob/main/src/core/isxCnmfeUtils.cpp#L265).

**Comment by tawantayron** [comment]
Hi Bruno.
First I want to say that I am very grateful for the attention. Second, your technique of using the estimated noise level for each trace is very interesting. I've also been using CaImAn to compare the results of both methods. But unfortunately, I don't understand C++ to understand your code on how to estimate the noise level. Could you please comment here on how this measurement is done? Or how can I use CaImAn to get a similar result?

PS: I think this technique can be highlighted more in the Github presentation because the idea is great.

**Comment by brunoboivin** [comment]
Inscopix CNMF-E estimates noise by averaging the high-frequency fluctuations along the traces using the code linked above. A fast Fourier transform is applied to each trace to convert it from the time domain to the frequency domain. High-frequency components from the corresponding power spectral density are averaged to obtain a noise estimate. CaImAn does not offer `dF over noise` as an option for the output units. Tips for matching the output units of both algorithms are available in our documentation [here](https://github.com/inscopix/inscopix-cnmfe/blob/main/docs/comparison_to_caiman.md#notes-on-matching-the-outputs-from-inscopix-cnmf-e-and-caiman-cnmf-e).

**Comment by tawantayron** [comment]
Thank you very much! I wish all of you the best!
