### ISSUE TITLE
Is it possible to read .isxd files as input?

### ISSUE THREAD

**Issue by zhoutianxun** [inscopix/inscopix-cnmfe#68]
This expects TIFF files as the input movie file format. I'm wondering if it's possible and if so, how to use .isxd files as the input?

**Comment by shayqn** [comment]
@zhoutianxun thanks for reaching out. 

To directly use .isxd files with Inscopix CNMF-E, you can use the Inscopix Data Processing Software (IDPS) Python API, which comes with the purchase of an Inscopix miniscope. The underlying code in IDPS and here is the same. 

You could also export your .isxd file to .tiff using IDPS, and then use the resulting .tiff as an input to this package. Hope that helps.
