### ISSUE TITLE
Potential bug in `isxCnmfeCoree.cpp`

### ISSUE THREAD

**Issue by ryanirl** [inscopix/inscopix-cnmfe#69]
Wouldn't it be `return m_mergeThresh;`?

https://github.com/inscopix/inscopix-cnmfe/blob/b5fbce53fc5d7ecc36b392eba2ad42ff57b895d7/src/core/isxCnmfeCore.cpp#L154-L157

**Comment by brunoboivin** [comment]
@ryanirl good catch, would you like to open a pull request to fix this issue? Luckily this function is not used anywhere in the algorithm at the moment.
